version: '3.0'

services:

 worker:
  build: .
  image: nubuntu:sparks
  hostname: worker
  env_file:
   - .env
  extra_hosts:
   - "master:${SPARK_MASTER_ADDR}"
  
  expose:
  - 8080
  - 7077
  - 8888
  - 8081
  - 4040
  - 7001
  - 7002
  - 7003
  - 7004
  - 7005
  - 7006
   
  
   
