version: '3'

services:

 worker:
  build: .
  image: nubuntu:sparks
  hostname: worker
  env_file:
   - .env

  extra_hosts:
   - "ak-ux330uak:${SPARK_MASTER_ADDR}"
  
  expose:
   - "7001"
   - "7002"
   - "7003"
   - "7004"
   - "7005"
   - "7006"
   - "8080"
   - "8081"
   - "6066"
   - "7077"
   - "4040"
   
  ports:
   - "4040:4040"
   - "6066:6066"
   - "7077:7077"
   - "8080:8080"

   
  
   
