version: '3.0'

services:

 worker:
  build: .
  image: nubuntu:sparks
  hostname: worker
  env_file:
   - .env
  extra_hosts:
   - "master:${SPARK_MASTER_ADDR}"
  volumes:
   - ${REQUIREMENTS_DOT_TXT_PATH}:/etc/docker-config/_requirements.txt
   - ${SPARK_ENV_DOT_SH_PATH}:/usr/local/spark/spark-2.2.1-bin-hadoop2.7/conf/spark-env.sh
  command: bash
  entrypoint: /etc/bootstrap.sh
  expose:
  - 8080
  - 7077
  - 8888
  - 8081
  - 4040
  - 7001
  - 7002
  - 7003
  - 7004
  - 7005
  - 7006
   
  
   
